app = "backend"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[restart]
  policy = "on-failure"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"

[processes]
  app = "uvicorn app.main:app --host 0.0.0.0 --port 8080"
  scheduler = "crond -f -l 2"

[http_service]
  processes = ["app"]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  
  [http_service.concurrency]
    type = "requests"
