app = "backend"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "uvicorn app.main:app --host 0.0.0.0 --port 8080"
  scheduler = "crond -f -l 2"

[http_service]
  processes = ["app"]
  internal_port = 8080
  force_https = true
